# 使用 Node 14 作为基础镜像
FROM node:latest

# 设置工作目录
WORKDIR /app

# 复制后端项目文件到镜像中
COPY backend/package.json backend/yarn.lock ./

# 安装后端项目依赖
RUN yarn install --frozen-lockfile

# 复制整个后端项目到镜像中
COPY backend/ ./

# 暴露后端服务端口（默认为 9000）
EXPOSE 9000

# 添加 Volume 定义
VOLUME ["/app/src/storage"]

# 启动后端项目
CMD yarn prisma-pull && yarn prisma-generate && yarn dev