# 使用官方 MySQL 8 镜像
FROM mysql:8.0.33

VOLUME ["/var/lib/mysql"]

# 设置环境变量，指定数据库名称、用户名和密码
ENV MYSQL_DATABASE=express_blog
ENV MYSQL_PASSWORD=12345678
ENV MYSQL_ROOT_PASSWORD=12345678

# 复制自定义的 MySQL 配置文件（如果需要）
# COPY mysql/my.cnf /etc/mysql/conf.d/my.cnf

# 复制初始化 SQL 脚本（如果有）
COPY backend/init.sql /docker-entrypoint-initdb.d/init.sql

# 暴露 MySQL 服务端口（默认为 3306）
EXPOSE 3306